triggers = {
    "blame": [
        "bad",
        "bastard",
        "fuck",
        "hate",
        "idiot",
        "lousy",
        "mean",
        "mediocre",
        "moron",
        "nasty",
        "quiet",
        "rude",
        "shut",
        "stop",
        "stupid",
        "suck",
        "terrible",
        "ugly",
        "useless",
        "worst",
        "worthless",
    ],
    "botname": ["sigurd"],
    "lyrics": ["lyrics"],
    "praise": [
        "amazing",
        "awesome",
        "cool",
        "decent",
        "fantastic",
        "good",
        "great",
        "love",
        "nice",
        "not bad",
        "sick",
        "smart",
        "sweet",
        "thank",
        "wow",
    ],
}
