# "<artist_name>": "<spotify_id>",
# where "spotify_id" is the token at the end of URLs such as: 
# https://open.spotify.com/artist/4MnZkh4dpNmTMPxkl4Ev5L 

monitored_artists = {
    "Adagio": "5QJvZ6s15Hgpjq7UKktjaZ",
    "Allen Lande": "2hxa4ytcni5FUIK8IR27tX",
    "Angra": "7IAXZaLTb6nkJr8RmVPn5y",
    "Arch Echo": "4ilweWzFHh6vrr7OOuDcUh",
    "Ayreon": "2RSApl0SXcVT8Yiy4UaPSt",
    "Beast In Black": "0rEuaTPLMhlViNCJrg3NEH",
    "Blackfield": "3xrzXKnScjOEoy172vsJMW",
    "Blind Guardian": "7jxJ25p0pPjk0MStloN6o6",
    "Body Count": "5KCph1z3jaSwhtwPzoYp6i",
    "Charlie Griffiths": "6jTFgiXjEiywkGfe44VwBZ",
    "DGM": "5Rq2C3wWiwL3NqjutXMt8e",
    "Deep Purple": "568ZhdwyaiCyOGJRtNYhWf",
    "Devin Townsend Project": "54Xuca1P5nDqfKYZGDfHxl",
    "Devin Townsend": "6uejjWIOshliv2Ho0OJAQN",
    "Dirty Loops": "5Apl0wL4OwNUDYkx69rMDQ",
    "Dream Theater": "2aaLAng2L2aWD2FClzwiep",
    "Fleshgod Apocalypse": "5ctFffJBdJe8PZL7W7NeML",
    "Freedom Call": "55RDuy7cQW2Dqrcz3Jjl6F",
    "Frost*": "1Ha9FtCeuoajMbOG4Kz2d7",
    "Galactikraken": "6vpkrtUi0qy4FlpbjF7EoS",
    "Haken": "2SRIVGDkdqQnrQdaXxDkJt",
    "Hammerfall": "2o18h28enlHxj887tATc58",
    "Helloween": "4pQN0GB0fNEEOfQCaWotsY",
    "Iron Maiden": "6mdiAmATAx73kdxrNrnlao",
    "Jaga Jazzist": "68HFSFMCZzyRjkkm9bv5Vt",
    "Jonathan Lundberg": "6t3AHrm1phB25xs2XpST7p",
    "Katatonia": "2CWWgbxApjbyByxBBCvGTm",
    "Knower": "7fVp0A6oCMfiQJihMnY0SZ",
    "Leo Abrahams": "6g4q7DPLaVqWGnfMpAb2Yd",
    "Leprous": "4lgrzShsg2FLA89UM2fdO5",
    "Liquid Tension Experiment": "0r1s1XoxdoXECGfyChzb2v",
    "Louis Cole": "6uIst176jhzooPMetg2rtH",
    "Meshuggah": "3ggwAqZD3lyT2sbovlmfQY",
    "Metallica": "2ye2Wgw4gimLv2eAKyk1NB",
    "Michael Romeo": "1u13Ufesdz3aVSYpL1bFue",
    "Moon Safari": "0Wr0oT0aCD6w7O25TPwnoX",
    "Myrath": "72500XOYPw5e7OgFWuW2Gl",
    "No-Man": "77BO4bYHfvTmVuG63wOuHX",
    "Opeth": "0ybFZ2Ab08V8hueghSXm6E",
    "Pagan's Mind": "0dvzEeVLv8VDQ0Rv36PZis",
    "Pain Of Salvation": "1uRpg2s2jNaxbmoNiJDGfd",
    "Paralydium": "65X6T9OJ2gXGpkc1DgrYgR",
    "Peter Gabriel": "7C4sUpWGlTy7IANjruj02I",
    "Plini": "3Gs10XJ4S4OEFrMRqZJcic",
    "Porcupine Tree": "5NXHXK6hOCotCF8lvGM1I0",
    "Running Wild": "7954VFaZClkL503srfV5PE",
    "Seal": "5GtMEZEeFFsuHY8ad4kOxv",
    "Snarky Puppy": "7ENzCHnmJUr20nUjoZ0zZ1",
    "Star One": "1W5pfX7IGyw9wCmfARg1pi",
    "StarSystems": "2JEmeK4NqHMXdtSMxCcWad",
    "Symphony X": "4MnZkh4dpNmTMPxkl4Ev5L",
    "The Rippingtons": "6hjqP9annof75B2TNBE0rO",
    "Thomas Bergersen": "6BF0bXbsdujMSMeFZBGcBq",
    "Todd Terje": "49gaZqfow2v8EEQmjGyEIw",
    "Toto": "0PFtn5NtBbbUNbU9EAmIWF",
    "Transatlantic": "4eOjprZV7J3pEjQOsdtLjC",
    "Twilight Force": "0tO6ALWmduAbneXoHmnl2T",
    "Ulver": "6bYFkBNvayh3nGqxcPp7Sv",
    "VOLA": "1HQjBwlj8FSHMhVaNQ4tEI",
    "Vanden Plas": "1ke5Q2ijh6Tm31kH2HELEe",
    "Vince DiCola": "5Q2nBzXfyXGIEf8KpHqeHn",
    "Wilderun": "0wQmcChWogcmsCThY2SKES",
}
